---
servers:
  vars:
    ansible_user: packer
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  hosts:
    semaphore:
      ansible_host: "10.88.0.202"

    debian-server:
      ansible_host: "10.88.0.205"
