---
- name: Create global proxy setup for all users
  ansible.builtin.copy:
    dest: "/etc/environment"
    content: |
      PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"
      export http_proxy="{{ proxy_server }}"
      export https_proxy="{{ proxy_server }}"
      export no_proxy={{ no_proxy }}
  register: global_proxy_result

- name: Setup apt source proxy
  ansible.builtin.copy:
    dest: "/etc/apt/apt.conf.d/proxy.conf"
    content: |
      Acquire::http::Proxy "{{ proxy_server }}";
      Acquire::https::Proxy "{{ proxy_server }}";
  register: apt_source_proxy
