---
# Default variables for the pyenv role

# Pyenv repository URL
pyenv_repo: "https://github.com/pyenv/pyenv.git"

# Pyenv installation directory
pyenv_root: "{{ ansible_env.HOME }}/.pyenv"

# Environment variables to be set
pyenv_environment:
  - { key: "PYENV_ROOT", value: "{{ pyenv_root }}" }
  - { key: "PATH", value: "{{ pyenv_root }}/bin:{{ ansible_env.PATH }}" }

# Pyenv python version
python_versions: ["3.9.6", "3.8.18"]
