---
- name: Update package source list
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install base packages defined in the list
  become: true
  ansible.builtin.apt:
    pkg: "{{ base_packages }}"

- name: Install user-defined extra packages
  become: true
  ansible.builtin.apt:
    pkg: "{{ extra_packages }}"

- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: true
