---
- name: Check if Docker is installed
  ansible.builtin.command:
    cmd: docker --version
  register: docker_installed
  failed_when: docker_installed.rc != 0 and docker_installed.rc != 1
  changed_when: false
  ignore_errors: true

- name: Install Docker with script
  ansible.builtin.shell:
    cmd: "wget -qO- https://get.docker.com/ | bash"
  register: installation_result
  become: true
  when: docker_installed is failed

- name: Enable docker to start at boot
  ansible.builtin.service:
    name: docker
    enabled: true
  when: installation_result is changed
  become: true

- name: Add user {{ user.name }} to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true
  when: installation_result is changed
  become: true

- name: "Post installation message"
  debug:
    msg: Use "newgrp docker" to use the group immediately
