---
- name: Set pyenv environment variables for bash (.bashrc)
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  when: ansible_env.SHELL is match("/bash$")

- name: Set pyenv environment variables for bash (.bash_profile or equivalent)
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  with_items:
    - .profile
    - .bash_profile
    - .bash_login
  when: ansible_env.SHELL is match("/bash$")
  ignore_errors: true
