---
- name: Set pyenv environment variables for zsh (.zshrc)
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  when: ansible_env.SHELL is match("/zsh$")

- name: Set pyenv environment variables for zsh (.zprofile or .zlogin)
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
  with_items:
    - .zprofile
    - .zlogin
  when: ansible_env.SHELL is match("/zsh$")
  ignore_errors: true
