---
- name: Check if Python version is already installed
  ansible.builtin.command: "{{ pyenv_root }}/bin/pyenv versions --bare"
  register: installed_python_versions
  changed_when: false

- name: Install Python versions using pyenv
  ansible.builtin.command: "{{ pyenv_root }}/bin/pyenv install {{ item }}"
  loop: "{{ python_versions }}"
  when: item not in installed_python_versions.stdout_lines
