---
# Main task file which includes other task files

- name: Install dependencies for pyenv
  ansible.builtin.include_tasks: install_dependencies.yml

- name: Install pyenv
  ansible.builtin.include_tasks: install_pyenv.yml

- name: Configure pyenv environment for bash
  ansible.builtin.include_tasks: configure_bash.yml

- name: Configure pyenv environment for zsh
  ansible.builtin.include_tasks: configure_zsh.yml

- name: Install specific Python versions using pyenv
  ansible.builtin.include_tasks: install_python_versions.yml
